### ISSUE TITLE
可否说一下API 的使用？

### ISSUE THREAD

**Issue by zysallen** [hcy1996/vue-toutiao#1]
是指首页请求新闻的api吗？我是从网页版的今日头条上捕获的，通过改变tag和min_behot_time这两个字段来获取数据。tag的参数（news_×××）你可以在f12下查看今日头条浏览每个标签查看。min_behot_time的参数就是时间戳（秒）。

**Comment by hcy1996** [comment]
是指首页请求新闻的api吗？我是从网页版的今日头条上捕获的，通过改变tag和min_behot_time这两个字段来获取数据。tag的参数（news_×××）你可以在f12下查看今日头条浏览每个标签查看。min_behot_time的参数就是时间戳（秒）。

**Comment by zysallen** [comment]
嗯，我想知道数据从哪里来，URL是什么，有没有跨域问题？

**Comment by hcy1996** [comment]
数据就是今日头条原版的数据，通过控制台network捕获的（建议每次刷新时找一下那条请求）。
URL我放在src/store/actions中，可自行查看。
是有跨域的，可以采取axios代理或者axios推荐的jsonp包方法。因为自己坑了，脚手架用的webpack-simple，所以无法配置proxyTable，所以采用了jsonp。
